//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov_organizacii_ByubzhetPlyus
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Дир отд по раб с кл.
    /// </summary>
    // *** Start programmer edit section *** (ДирОтдПоРабСКл CustomAttributes)

    // *** End programmer edit section *** (ДирОтдПоРабСКл CustomAttributes)
    [AutoAltered()]
    [Caption("Директор")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДиректорE", new string[] {
            "idДиректора as \'Id директора\'",
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "НомерТелефона as \'Номер телефона\'",
            "НомерПаспорта as \'Номер паспорта\'",
            "СерияПаспорта as \'Серия паспорта\'"})]
    [View("ДиректорL", new string[] {
            "idДиректора as \'Id директора\'",
            "Фамилия as \'Фамилия\'",
            "Имя as \'Имя\'",
            "Отчество as \'Отчество\'",
            "НомерТелефона as \'Номер телефона\'",
            "НомерПаспорта as \'Номер паспорта\'",
            "СерияПаспорта as \'Серия паспорта\'"})]
    public class ДирОтдПоРабСКл : ICSSoft.STORMNET.DataObject
    {
        
        private int fidДиректора;
        
        private string fФамилия;
        
        private string fИмя;
        
        private string fОтчество;
        
        private string fНомерТелефона;
        
        private string fНомерПаспорта;
        
        private string fСерияПаспорта;
        
        // *** Start programmer edit section *** (ДирОтдПоРабСКл CustomMembers)

        // *** End programmer edit section *** (ДирОтдПоРабСКл CustomMembers)

        
        /// <summary>
        /// idДиректора.
        /// </summary>
        // *** Start programmer edit section *** (ДирОтдПоРабСКл.idДиректора CustomAttributes)

        // *** End programmer edit section *** (ДирОтдПоРабСКл.idДиректора CustomAttributes)
        public virtual int idДиректора
        {
            get
            {
                // *** Start programmer edit section *** (ДирОтдПоРабСКл.idДиректора Get start)

                // *** End programmer edit section *** (ДирОтдПоРабСКл.idДиректора Get start)
                int result = this.fidДиректора;
                // *** Start programmer edit section *** (ДирОтдПоРабСКл.idДиректора Get end)

                // *** End programmer edit section *** (ДирОтдПоРабСКл.idДиректора Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДирОтдПоРабСКл.idДиректора Set start)

                // *** End programmer edit section *** (ДирОтдПоРабСКл.idДиректора Set start)
                this.fidДиректора = value;
                // *** Start programmer edit section *** (ДирОтдПоРабСКл.idДиректора Set end)

                // *** End programmer edit section *** (ДирОтдПоРабСКл.idДиректора Set end)
            }
        }
        
        /// <summary>
        /// Имя.
        /// </summary>
        // *** Start programmer edit section *** (ДирОтдПоРабСКл.Имя CustomAttributes)

        // *** End programmer edit section *** (ДирОтдПоРабСКл.Имя CustomAttributes)
        [StrLen(255)]
        public virtual string Имя
        {
            get
            {
                // *** Start programmer edit section *** (ДирОтдПоРабСКл.Имя Get start)

                // *** End programmer edit section *** (ДирОтдПоРабСКл.Имя Get start)
                string result = this.fИмя;
                // *** Start programmer edit section *** (ДирОтдПоРабСКл.Имя Get end)

                // *** End programmer edit section *** (ДирОтдПоРабСКл.Имя Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДирОтдПоРабСКл.Имя Set start)

                // *** End programmer edit section *** (ДирОтдПоРабСКл.Имя Set start)
                this.fИмя = value;
                // *** Start programmer edit section *** (ДирОтдПоРабСКл.Имя Set end)

                // *** End programmer edit section *** (ДирОтдПоРабСКл.Имя Set end)
            }
        }
        
        /// <summary>
        /// НомерПаспорта.
        /// </summary>
        // *** Start programmer edit section *** (ДирОтдПоРабСКл.НомерПаспорта CustomAttributes)

        // *** End programmer edit section *** (ДирОтдПоРабСКл.НомерПаспорта CustomAttributes)
        [StrLen(255)]
        public virtual string НомерПаспорта
        {
            get
            {
                // *** Start programmer edit section *** (ДирОтдПоРабСКл.НомерПаспорта Get start)

                // *** End programmer edit section *** (ДирОтдПоРабСКл.НомерПаспорта Get start)
                string result = this.fНомерПаспорта;
                // *** Start programmer edit section *** (ДирОтдПоРабСКл.НомерПаспорта Get end)

                // *** End programmer edit section *** (ДирОтдПоРабСКл.НомерПаспорта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДирОтдПоРабСКл.НомерПаспорта Set start)

                // *** End programmer edit section *** (ДирОтдПоРабСКл.НомерПаспорта Set start)
                this.fНомерПаспорта = value;
                // *** Start programmer edit section *** (ДирОтдПоРабСКл.НомерПаспорта Set end)

                // *** End programmer edit section *** (ДирОтдПоРабСКл.НомерПаспорта Set end)
            }
        }
        
        /// <summary>
        /// НомерТелефона.
        /// </summary>
        // *** Start programmer edit section *** (ДирОтдПоРабСКл.НомерТелефона CustomAttributes)

        // *** End programmer edit section *** (ДирОтдПоРабСКл.НомерТелефона CustomAttributes)
        [StrLen(255)]
        public virtual string НомерТелефона
        {
            get
            {
                // *** Start programmer edit section *** (ДирОтдПоРабСКл.НомерТелефона Get start)

                // *** End programmer edit section *** (ДирОтдПоРабСКл.НомерТелефона Get start)
                string result = this.fНомерТелефона;
                // *** Start programmer edit section *** (ДирОтдПоРабСКл.НомерТелефона Get end)

                // *** End programmer edit section *** (ДирОтдПоРабСКл.НомерТелефона Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДирОтдПоРабСКл.НомерТелефона Set start)

                // *** End programmer edit section *** (ДирОтдПоРабСКл.НомерТелефона Set start)
                this.fНомерТелефона = value;
                // *** Start programmer edit section *** (ДирОтдПоРабСКл.НомерТелефона Set end)

                // *** End programmer edit section *** (ДирОтдПоРабСКл.НомерТелефона Set end)
            }
        }
        
        /// <summary>
        /// Отчество.
        /// </summary>
        // *** Start programmer edit section *** (ДирОтдПоРабСКл.Отчество CustomAttributes)

        // *** End programmer edit section *** (ДирОтдПоРабСКл.Отчество CustomAttributes)
        [StrLen(255)]
        public virtual string Отчество
        {
            get
            {
                // *** Start programmer edit section *** (ДирОтдПоРабСКл.Отчество Get start)

                // *** End programmer edit section *** (ДирОтдПоРабСКл.Отчество Get start)
                string result = this.fОтчество;
                // *** Start programmer edit section *** (ДирОтдПоРабСКл.Отчество Get end)

                // *** End programmer edit section *** (ДирОтдПоРабСКл.Отчество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДирОтдПоРабСКл.Отчество Set start)

                // *** End programmer edit section *** (ДирОтдПоРабСКл.Отчество Set start)
                this.fОтчество = value;
                // *** Start programmer edit section *** (ДирОтдПоРабСКл.Отчество Set end)

                // *** End programmer edit section *** (ДирОтдПоРабСКл.Отчество Set end)
            }
        }
        
        /// <summary>
        /// СерияПаспорта.
        /// </summary>
        // *** Start programmer edit section *** (ДирОтдПоРабСКл.СерияПаспорта CustomAttributes)

        // *** End programmer edit section *** (ДирОтдПоРабСКл.СерияПаспорта CustomAttributes)
        [StrLen(255)]
        public virtual string СерияПаспорта
        {
            get
            {
                // *** Start programmer edit section *** (ДирОтдПоРабСКл.СерияПаспорта Get start)

                // *** End programmer edit section *** (ДирОтдПоРабСКл.СерияПаспорта Get start)
                string result = this.fСерияПаспорта;
                // *** Start programmer edit section *** (ДирОтдПоРабСКл.СерияПаспорта Get end)

                // *** End programmer edit section *** (ДирОтдПоРабСКл.СерияПаспорта Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДирОтдПоРабСКл.СерияПаспорта Set start)

                // *** End programmer edit section *** (ДирОтдПоРабСКл.СерияПаспорта Set start)
                this.fСерияПаспорта = value;
                // *** Start programmer edit section *** (ДирОтдПоРабСКл.СерияПаспорта Set end)

                // *** End programmer edit section *** (ДирОтдПоРабСКл.СерияПаспорта Set end)
            }
        }
        
        /// <summary>
        /// Фамилия.
        /// </summary>
        // *** Start programmer edit section *** (ДирОтдПоРабСКл.Фамилия CustomAttributes)

        // *** End programmer edit section *** (ДирОтдПоРабСКл.Фамилия CustomAttributes)
        [StrLen(255)]
        public virtual string Фамилия
        {
            get
            {
                // *** Start programmer edit section *** (ДирОтдПоРабСКл.Фамилия Get start)

                // *** End programmer edit section *** (ДирОтдПоРабСКл.Фамилия Get start)
                string result = this.fФамилия;
                // *** Start programmer edit section *** (ДирОтдПоРабСКл.Фамилия Get end)

                // *** End programmer edit section *** (ДирОтдПоРабСКл.Фамилия Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДирОтдПоРабСКл.Фамилия Set start)

                // *** End programmer edit section *** (ДирОтдПоРабСКл.Фамилия Set start)
                this.fФамилия = value;
                // *** Start programmer edit section *** (ДирОтдПоРабСКл.Фамилия Set end)

                // *** End programmer edit section *** (ДирОтдПоРабСКл.Фамилия Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДиректорE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДиректорE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДиректорE", typeof(IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov_organizacii_ByubzhetPlyus.ДирОтдПоРабСКл));
                }
            }
            
            /// <summary>
            /// "ДиректорL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДиректорL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДиректорL", typeof(IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov_organizacii_ByubzhetPlyus.ДирОтдПоРабСКл));
                }
            }
        }
    }
}
