//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov_organizacii_ByubzhetPlyus
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Ед времени.
    /// </summary>
    // *** Start programmer edit section *** (ЕдВремени CustomAttributes)

    // *** End programmer edit section *** (ЕдВремени CustomAttributes)
    public enum ЕдВремени
    {
        
        // *** Start programmer edit section *** (ЕдВремени.Год CustomAttributes)

        // *** End programmer edit section *** (ЕдВремени.Год CustomAttributes)
        [Caption("Год")]
        Год,
        
        // *** Start programmer edit section *** (ЕдВремени.Месяц CustomAttributes)

        // *** End programmer edit section *** (ЕдВремени.Месяц CustomAttributes)
        [Caption("Месяц")]
        Месяц,
        
        // *** Start programmer edit section *** (ЕдВремени.День CustomAttributes)

        // *** End programmer edit section *** (ЕдВремени.День CustomAttributes)
        [Caption("День")]
        День,
        
        // *** Start programmer edit section *** (ЕдВремени.Час CustomAttributes)

        // *** End programmer edit section *** (ЕдВремени.Час CustomAttributes)
        [Caption("Час")]
        Час,
    }
}
