//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov_organizacii_ByubzhetPlyus
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Расчет ост врем.
    /// </summary>
    // *** Start programmer edit section *** (РасчетОстВрем CustomAttributes)

    // *** End programmer edit section *** (РасчетОстВрем CustomAttributes)
    [AutoAltered()]
    [Caption("Расчет времени")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РасчетВремениE", new string[] {
            "Дата as \'Дата\'",
            "Договор as \'Номер договора\'",
            "Договор.Статус as \'Статус\'",
            "Договор.Длительность as \'Длительность\'",
            "Договор.ЕдВремени as \'Единица времени\'",
            "Использовано as \'Использовано\'",
            "Доступно as \'Доступно\'"})]
    [AssociatedDetailViewAttribute("РасчетВремениE", "ОказУслуг", "ОказУслугE", true, "", "Оказ услуг", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("РасчетВремениE", "Договор", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номер")]
    [View("РасчетВремениL", new string[] {
            "Дата as \'Дата\'",
            "Договор.Номер as \'Номер договора\'",
            "Договор.Статус as \'Статус\'",
            "Договор.Длительность as \'Длительность\'",
            "Договор.ЕдВремени as \'Единица времени\'",
            "Использовано as \'Использовано\'",
            "Доступно as \'Доступно\'"})]
    public class РасчетОстВрем : ICSSoft.STORMNET.DataObject
    {
        
        private double fДоступно;
        
        private System.DateTime fДата;
        
        private double fИспользовано;
        
        private IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov_organizacii_ByubzhetPlyus.Договор fДоговор;
        
        private IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov_organizacii_ByubzhetPlyus.DetailArrayOfОказУслуг fОказУслуг;
        
        // *** Start programmer edit section *** (РасчетОстВрем CustomMembers)

        // *** End programmer edit section *** (РасчетОстВрем CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (РасчетОстВрем.Дата CustomAttributes)

        // *** End programmer edit section *** (РасчетОстВрем.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (РасчетОстВрем.Дата Get start)

                // *** End programmer edit section *** (РасчетОстВрем.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (РасчетОстВрем.Дата Get end)

                // *** End programmer edit section *** (РасчетОстВрем.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетОстВрем.Дата Set start)

                // *** End programmer edit section *** (РасчетОстВрем.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (РасчетОстВрем.Дата Set end)

                // *** End programmer edit section *** (РасчетОстВрем.Дата Set end)
            }
        }
        
        /// <summary>
        /// Доступно.
        /// </summary>
        // *** Start programmer edit section *** (РасчетОстВрем.Доступно CustomAttributes)

        // *** End programmer edit section *** (РасчетОстВрем.Доступно CustomAttributes)
        public virtual double Доступно
        {
            get
            {
                // *** Start programmer edit section *** (РасчетОстВрем.Доступно Get start)

                // *** End programmer edit section *** (РасчетОстВрем.Доступно Get start)
                double result = this.fДоступно;
                // *** Start programmer edit section *** (РасчетОстВрем.Доступно Get end)

                // *** End programmer edit section *** (РасчетОстВрем.Доступно Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетОстВрем.Доступно Set start)

                // *** End programmer edit section *** (РасчетОстВрем.Доступно Set start)
                this.fДоступно = value;
                // *** Start programmer edit section *** (РасчетОстВрем.Доступно Set end)

                // *** End programmer edit section *** (РасчетОстВрем.Доступно Set end)
            }
        }
        
        /// <summary>
        /// Использовано.
        /// </summary>
        // *** Start programmer edit section *** (РасчетОстВрем.Использовано CustomAttributes)

        // *** End programmer edit section *** (РасчетОстВрем.Использовано CustomAttributes)
        public virtual double Использовано
        {
            get
            {
                // *** Start programmer edit section *** (РасчетОстВрем.Использовано Get start)

                // *** End programmer edit section *** (РасчетОстВрем.Использовано Get start)
                double result = this.fИспользовано;
                // *** Start programmer edit section *** (РасчетОстВрем.Использовано Get end)

                // *** End programmer edit section *** (РасчетОстВрем.Использовано Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетОстВрем.Использовано Set start)

                // *** End programmer edit section *** (РасчетОстВрем.Использовано Set start)
                this.fИспользовано = value;
                // *** Start programmer edit section *** (РасчетОстВрем.Использовано Set end)

                // *** End programmer edit section *** (РасчетОстВрем.Использовано Set end)
            }
        }
        
        /// <summary>
        /// Расчет ост врем.
        /// </summary>
        // *** Start programmer edit section *** (РасчетОстВрем.Договор CustomAttributes)

        // *** End programmer edit section *** (РасчетОстВрем.Договор CustomAttributes)
        [PropertyStorage(new string[] {
                "Договор"})]
        [NotNull()]
        public virtual IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov_organizacii_ByubzhetPlyus.Договор Договор
        {
            get
            {
                // *** Start programmer edit section *** (РасчетОстВрем.Договор Get start)

                // *** End programmer edit section *** (РасчетОстВрем.Договор Get start)
                IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov_organizacii_ByubzhetPlyus.Договор result = this.fДоговор;
                // *** Start programmer edit section *** (РасчетОстВрем.Договор Get end)

                // *** End programmer edit section *** (РасчетОстВрем.Договор Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетОстВрем.Договор Set start)

                // *** End programmer edit section *** (РасчетОстВрем.Договор Set start)
                this.fДоговор = value;
                // *** Start programmer edit section *** (РасчетОстВрем.Договор Set end)

                // *** End programmer edit section *** (РасчетОстВрем.Договор Set end)
            }
        }
        
        /// <summary>
        /// Расчет ост врем.
        /// </summary>
        // *** Start programmer edit section *** (РасчетОстВрем.ОказУслуг CustomAttributes)

        // *** End programmer edit section *** (РасчетОстВрем.ОказУслуг CustomAttributes)
        public virtual IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov_organizacii_ByubzhetPlyus.DetailArrayOfОказУслуг ОказУслуг
        {
            get
            {
                // *** Start programmer edit section *** (РасчетОстВрем.ОказУслуг Get start)

                // *** End programmer edit section *** (РасчетОстВрем.ОказУслуг Get start)
                if ((this.fОказУслуг == null))
                {
                    this.fОказУслуг = new IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov_organizacii_ByubzhetPlyus.DetailArrayOfОказУслуг(this);
                }
                IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov_organizacii_ByubzhetPlyus.DetailArrayOfОказУслуг result = this.fОказУслуг;
                // *** Start programmer edit section *** (РасчетОстВрем.ОказУслуг Get end)

                // *** End programmer edit section *** (РасчетОстВрем.ОказУслуг Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (РасчетОстВрем.ОказУслуг Set start)

                // *** End programmer edit section *** (РасчетОстВрем.ОказУслуг Set start)
                this.fОказУслуг = value;
                // *** Start programmer edit section *** (РасчетОстВрем.ОказУслуг Set end)

                // *** End programmer edit section *** (РасчетОстВрем.ОказУслуг Set end)
            }
        }
        
        // *** Start programmer edit section *** (РасчетОстВрем.Отправить CustomAttributes)

        // *** End programmer edit section *** (РасчетОстВрем.Отправить CustomAttributes)
        [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
        public virtual void Отправить()
        {
            // *** Start programmer edit section *** (РасчетОстВрем.Отправить method implementation)

            return;
            // *** End programmer edit section *** (РасчетОстВрем.Отправить method implementation)
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РасчетВремениE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасчетВремениE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасчетВремениE", typeof(IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov_organizacii_ByubzhetPlyus.РасчетОстВрем));
                }
            }
            
            /// <summary>
            /// "РасчетВремениL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасчетВремениL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасчетВремениL", typeof(IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov_organizacii_ByubzhetPlyus.РасчетОстВрем));
                }
            }
        }
    }
}
