//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov_organizacii_ByubzhetPlyus
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Статус.
    /// </summary>
    // *** Start programmer edit section *** (Статус CustomAttributes)

    // *** End programmer edit section *** (Статус CustomAttributes)
    public enum Статус
    {
        
        // *** Start programmer edit section *** (Статус.Заключен CustomAttributes)

        // *** End programmer edit section *** (Статус.Заключен CustomAttributes)
        [Caption("Заключен")]
        Заключен,
        
        // *** Start programmer edit section *** (Статус.Расторжен CustomAttributes)

        // *** End programmer edit section *** (Статус.Расторжен CustomAttributes)
        [Caption("Расторжен")]
        Расторжен,
    }
}
