//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov_organizacii_ByubzhetPlyus
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тип договора.
    /// </summary>
    // *** Start programmer edit section *** (ТипДоговора CustomAttributes)

    // *** End programmer edit section *** (ТипДоговора CustomAttributes)
    public enum ТипДоговора
    {
        
        // *** Start programmer edit section *** (ТипДоговора.Краткосрочный CustomAttributes)

        // *** End programmer edit section *** (ТипДоговора.Краткосрочный CustomAttributes)
        [Caption("Краткосрочный")]
        Краткосрочный,
        
        // *** Start programmer edit section *** (ТипДоговора.Долгосрочный CustomAttributes)

        // *** End programmer edit section *** (ТипДоговора.Долгосрочный CustomAttributes)
        [Caption("Долгосрочный")]
        Долгосрочный,
    }
}
