//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov_organizacii_ByubzhetPlyus
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Услуги.
    /// </summary>
    // *** Start programmer edit section *** (Услуги CustomAttributes)

    // *** End programmer edit section *** (Услуги CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("УслугиE", new string[] {
            "Наименование as \'Наименование\'",
            "ЗатрВрем as \'Затраченное время\'",
            "ЕдВремени as \'Единица времени\'"})]
    [View("УслугиL", new string[] {
            "Наименование as \'Наименование\'",
            "ЗатрВрем as \'Затраченное время\'",
            "ЕдВремени as \'Единица времени\'"})]
    public class Услуги : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov_organizacii_ByubzhetPlyus.Услуга fНаименование;
        
        private double fЗатрВрем;
        
        private IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov_organizacii_ByubzhetPlyus.ЕдВремени fЕдВремени;
        
        // *** Start programmer edit section *** (Услуги CustomMembers)

        // *** End programmer edit section *** (Услуги CustomMembers)

        
        /// <summary>
        /// ЕдВремени.
        /// </summary>
        // *** Start programmer edit section *** (Услуги.ЕдВремени CustomAttributes)

        // *** End programmer edit section *** (Услуги.ЕдВремени CustomAttributes)
        public virtual IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov_organizacii_ByubzhetPlyus.ЕдВремени ЕдВремени
        {
            get
            {
                // *** Start programmer edit section *** (Услуги.ЕдВремени Get start)

                // *** End programmer edit section *** (Услуги.ЕдВремени Get start)
                IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov_organizacii_ByubzhetPlyus.ЕдВремени result = this.fЕдВремени;
                // *** Start programmer edit section *** (Услуги.ЕдВремени Get end)

                // *** End programmer edit section *** (Услуги.ЕдВремени Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Услуги.ЕдВремени Set start)

                // *** End programmer edit section *** (Услуги.ЕдВремени Set start)
                this.fЕдВремени = value;
                // *** Start programmer edit section *** (Услуги.ЕдВремени Set end)

                // *** End programmer edit section *** (Услуги.ЕдВремени Set end)
            }
        }
        
        /// <summary>
        /// ЗатрВрем.
        /// </summary>
        // *** Start programmer edit section *** (Услуги.ЗатрВрем CustomAttributes)

        // *** End programmer edit section *** (Услуги.ЗатрВрем CustomAttributes)
        public virtual double ЗатрВрем
        {
            get
            {
                // *** Start programmer edit section *** (Услуги.ЗатрВрем Get start)

                // *** End programmer edit section *** (Услуги.ЗатрВрем Get start)
                double result = this.fЗатрВрем;
                // *** Start programmer edit section *** (Услуги.ЗатрВрем Get end)

                // *** End programmer edit section *** (Услуги.ЗатрВрем Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Услуги.ЗатрВрем Set start)

                // *** End programmer edit section *** (Услуги.ЗатрВрем Set start)
                this.fЗатрВрем = value;
                // *** Start programmer edit section *** (Услуги.ЗатрВрем Set end)

                // *** End programmer edit section *** (Услуги.ЗатрВрем Set end)
            }
        }
        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Услуги.Наименование CustomAttributes)

        // *** End programmer edit section *** (Услуги.Наименование CustomAttributes)
        public virtual IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov_organizacii_ByubzhetPlyus.Услуга Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Услуги.Наименование Get start)

                // *** End programmer edit section *** (Услуги.Наименование Get start)
                IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov_organizacii_ByubzhetPlyus.Услуга result = this.fНаименование;
                // *** Start programmer edit section *** (Услуги.Наименование Get end)

                // *** End programmer edit section *** (Услуги.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Услуги.Наименование Set start)

                // *** End programmer edit section *** (Услуги.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Услуги.Наименование Set end)

                // *** End programmer edit section *** (Услуги.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "УслугиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УслугиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УслугиE", typeof(IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov_organizacii_ByubzhetPlyus.Услуги));
                }
            }
            
            /// <summary>
            /// "УслугиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View УслугиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("УслугиL", typeof(IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov_organizacii_ByubzhetPlyus.Услуги));
                }
            }
        }
    }
}
