//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Modul_ucheta_sroka_dejjstviya_zaklyuchennykh_dogovorov_organizacii_ByubzhetPlyus
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Услуга.
    /// </summary>
    // *** Start programmer edit section *** (Услуга CustomAttributes)

    // *** End programmer edit section *** (Услуга CustomAttributes)
    public enum Услуга
    {
        
        // *** Start programmer edit section *** (Услуга.ПомЗакрМес CustomAttributes)

        // *** End programmer edit section *** (Услуга.ПомЗакрМес CustomAttributes)
        [Caption("Помощь в закрытии месяца")]
        ПомЗакрМес,
        
        // *** Start programmer edit section *** (Услуга.РешУстнВопр CustomAttributes)

        // *** End programmer edit section *** (Услуга.РешУстнВопр CustomAttributes)
        [Caption("Решение устных вопросов")]
        РешУстнВопр,
        
        // *** Start programmer edit section *** (Услуга.ПомПровДок CustomAttributes)

        // *** End programmer edit section *** (Услуга.ПомПровДок CustomAttributes)
        [Caption("Помощь в проведении документа")]
        ПомПровДок,
    }
}
